sonar.projectKey=e-commerce-pw-as
sonar.projectName=E-commerce Playwright AS
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,test-results/**,playwright-report/**,blob-report/**,storageState.json

sonar.tests=tests/
sonar.test.inclusions=**/*.spec.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8